### ISSUE TITLE
Multiline match + join lines

### ISSUE THREAD

**Issue by towerofnix** [liam4/table-util#1]
How can we get the description text out of this?

```
+-----------------------------+
|            Slime            |
+-----------------------------+
| Slimes are amazing. I don't |
| know what you mean when you |
| say that they're furry,     |
| though.                     |
+-----------------------------+
```

I think something like this might do well:

``` yaml
match: # regex to get text inbetween lines
group: # ^^
lines: # lines to use match/group on
  begin: 4 # slimes are amazing..
  end: 7 # ..though
join: ' ' # join each line by spaces
```
