### ISSUE TITLE
Multiline begin/end regexes

### ISSUE THREAD

**Issue by towerofnix** [liam4/table-util#2]
Following #1 - what if the description has a varied amount of lines?

For example, given these two tables:

```
+-----------------------------+
|            Slime            |
+-----------------------------+
| Slimes are amazing. I don't |
| know what you mean when you |
| say that they're furry,     |
| though.                     |
+-----------------------------+

+-----------------------------+
|          Ratattack          |
+-----------------------------+
| Now THESE are furry!        |
+-----------------------------+
```

How can we match the description of both of these?

I'd probably go with something like this:

``` yaml
tableSplit: "\n\n"
getData:
  description:
    match: '\|\s(.+?(?=\s+\|))'
    group: 1
  lines:
    begin: 3
    end:
      regex: '\+-----------------------------\+'
  join: ' '
```

**Comment by towerofnix** [comment]
There should also probably be a `startCanBeEnd: (true/false)` option, default false.

**Comment by towerofnix** [comment]
Demo.

### test.txt

```
Jokes
Jokes
Jokes
Pigs!
AHHHH
No pigs.

Jokes
Jokes
Jokes
Jokes
Jokes
Jokes
Jokes
Pigs!
Hi hi hi
No pigs.

Jokes
Jokes
Jokes
Jokes
Pigs!
Hey hey hey!
How's it going?
No pigs.
Jokes
Jokes
```

### test.rules.yaml

``` yaml
tableSplit: "\n\n"
getData:
  demo:
    lines:
      begin: 'Pigs!'
      end: 'No pigs\.'
    join: '\n'
    regex: '^.*$'
template: |
  Value: $(demo)
```

### test.json

``` json
[
  "Value: Pigs!\\nAHHHH\n",
  "Value: Pigs!\\nHi hi hi\n",
  "Value: Pigs!\\nHey hey hey!\\nHow's it going?\n"
]
```
