### ISSUE TITLE
Inclusive line range

### ISSUE THREAD

**Issue by towerofnix** [liam4/table-util#3]
Following #2 - If the begin and/or end is a regex, how can we get the things that are only _between_ those lines?

Should be simple enough:

``` yaml
lines:
  begin: # begin regex
  end: # end regex
  inclusive: false
```

lines.inclusive should be true by default.

**Comment by towerofnix** [comment]
Demo:

### test.txt

[Same as before](https://github.com/liam4/table-util/issues/2#issuecomment-226773984).

### rules.yaml

``` yaml
tableSplit: "\n\n"
getData:
  demo:
    lines:
      begin: 'Pigs!'
      end: 'No pigs\.'
      inclusive: false # <--
    join: '\n'
    regex: '^.*$'
template: |
  Value: $(demo)
```

### test.json

``` json
[
  "Value: AHHHH\n",
  "Value: Hi hi hi\n",
  "Value: Hey hey hey!\\nHow's it going?\n"
]
```

PS, here's test.json were we to run the previous example's YAML now:

``` json
[
  "Value: Pigs!\\nAHHHH\\nNo pigs.\n",
  "Value: Pigs!\\nHi hi hi\\nNo pigs.\n",
  "Value: Pigs!\\nHey hey hey!\\nHow's it going?\\nNo pigs.\n"
]
```
