### ISSUE TITLE
Move join to lines.join

### ISSUE THREAD

**Issue by towerofnix** [liam4/table-util#4]
Following #1. Just move `join` to `lines.join`:

``` yaml
lines:
  begin: 1
  end: 2
join: ' '

# will be changed to
lines:
  begin: 1
  end: 2
  join: ' '
```

Because `join` will only apply when there are multiple lines for a match.
