### ISSUE TITLE
Relative line number

### ISSUE THREAD

**Issue by towerofnix** [liam4/table-util#5]
In this example:

```
  /----- Hello world! -----\
  | This is just an        |
  | example. I'm working   |
  | on it :)               |
  +------------------------+
  \--     CODE:  42      --/

  /----- INTERMISSION -----\
  | Quick reminder that    |
  | the codes are fake!    |
  +------------------------+
  \--     CODE: 123      --/
```

..how can we get the `CODE`?

We know it comes after the description, and we're already matching that, so maybe we should just make the line number relative to the previous match?

``` yaml
getData:
  description: # ...
  code:
    line: +1
    lineRelativeToPrevious: true # <----
    regex: 'CODE:\s+([0-9]+)\s+'
    group: 1
```

PS it would be relative to the _end_ of the previous match.
